framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: 'alquiler_equipos_sonido'

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        app: cache.adapter.filesystem

        # Uncomment below to use Redis for cache storage.
        # app: cache.adapter.redis
        # default_redis_provider: 'redis://localhost'

        # Uncomment below to use APCu for cache storage.
        # app: cache.adapter.apcu

        # Namespaced pools use the above "app" backend by default.
        pools:
            # Example dedicated cache pool for a specific use case.
            my_dedicated_cache:
                adapter: cache.adapter.filesystem
                provider: 'cache.adapter.redis'
                default_lifetime: 3600 # Cache entries live for 1 hour by default.

            # Uncomment and configure below for additional cache pools.
            # another_cache_pool:
            #     adapter: cache.adapter.apcu
            #     default_lifetime: 600 # Cache entries live for 10 minutes by default.
