# Configuration for debugging in the development environment

when@dev:
    debug:
        # Forwards VarDumper Data clones to a centralized server allowing to inspect dumps on CLI or in your browser.
        # See the "server:dump" command to start a new server.
        dump_destination: "tcp://%env(VAR_DUMPER_SERVER)%"
        # Replace '%env(VAR_DUMPER_SERVER)%' with the actual environment variable or a specific address
        # Example: "tcp://127.0.0.1:9912" for local development
