# Configuration for Symfony Framework
# For more details, see: https://symfony.com/doc/current/reference/configuration/framework.html

framework:
    secret: '%env(APP_SECRET)%'
    # Secret key for encrypting cookies and other sensitive data

    # Enable CSRF protection globally
    csrf_protection: true

    # Session configuration
    session:
        handler_id: null
        cookie_secure: auto  # Secure cookies if the application is served over HTTPS
        cookie_samesite: 'lax'  # Defines the SameSite policy for cookies
        cookie_lifetime: 3600  # Optional: Set cookie lifetime to 1 hour
        cookie_path: '/'  # Optional: Define the cookie path for better security
        cookie_httponly: true  # Ensure cookies are not accessible via JavaScript for better security

    # Enable ESI (Edge Side Includes) for HTTP caching and fragments
    esi: true

    # Enable the rendering of fragments in your templates
    fragments: true

    # HTTP Cache configuration
    http_cache:
        enabled: true
        default_ttl: 3600  # Default TTL for cached responses
        private_headers: ['Authorization', 'Cookie']
        vary: ['Accept-Encoding']  # Optional: Specify HTTP headers that should cause the cache to vary

    # Profiler configuration
    profiler:
        only_exceptions: false  # Collect data for all requests, not just exceptions
        collect: true  # Ensure that data is collected for each request
        enabled: '%kernel.debug%'  # Enable profiler only in debug mode

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file  # Use mock file storage for sessions in tests
