framework:
    messenger:
        failure_transport: failed

        transports:
            # Asynchronous transport configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000  # Check for delayed messages every 60 seconds
                retry_strategy:
                    max_retries: 5  # Increased maximum retries to 5
                    multiplier: 2
                    max_delay: 600000  # Max delay set to 10 minutes
                    delay: 1000  # Initial delay of 1 second
            # Failed messages transport
            failed: 'doctrine://default?queue_name=failed'
            
            # Uncomment to enable synchronous transport for debugging purposes
            # sync: 'sync://'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []
            messenger.bus.commands: []  # Added separate bus for command messages
            messenger.bus.events: []    # Added separate bus for event messages

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async

            # Example: Custom message routing
            # 'App\Message\ImportantNotification': [async, sync]  # Route to both async and sync transports
