# Security configuration for Symfony
# For more details, see: https://symfony.com/doc/current/security.html

security:
    # Configure password hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        # Automatically configure the password hasher based on best practices and Symfony defaults.

    # User providers to load user data from various sources
    providers:
        users_in_memory:
            memory: null  # In-memory user storage for simplicity, replace with a database provider for production

        database_users:
            entity:
                class: App\Entity\User
                property: email  # Use the email property to load users from the database

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            # Disable security for development routes to simplify access.

        main:
            lazy: true
            provider: database_users  # Use the database provider for the main firewall

            form_login:
                login_path: login
                check_path: login
                default_target_path: /dashboard
                always_use_default_target_path: true
                username_parameter: email
                password_parameter: password
                # Configure form login with paths and parameter names

            logout:
                path: logout
                target: /
                # Configure logout path and redirect to home page

            anonymous: true  # Enable anonymous access for initial setup

            switch_user:
                role: ROLE_ADMIN  # Only allow users with the ROLE_ADMIN to impersonate others

    # Access control rules for various paths
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # Define access control rules for different routes

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4  # Minimum cost for bcrypt to speed up tests
                time_cost: 3  # Minimum time cost for argon to speed up tests
                memory_cost: 10  # Minimum memory cost for argon to speed up tests
                # Lower security settings for password hashing in test environment to speed up tests
