when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error

    _profiler:
        resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
        prefix: /_profiler
