# Configuration for routes specific to the development environment

when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
        prefix: /_error

    _profiler:
        resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
        prefix: /_profiler

    _debug:
        resource: '@FrameworkBundle/Resources/config/routing/debug.xml'
        prefix: /_debug

    _web_profiler:
        resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
        prefix: /_web_profiler
