when@dev:
    web_profiler_wdt:
        resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
        prefix: /_wdt

    web_profiler_profiler:
        resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
        prefix: /_profiler

    web_profiler_debug:
        resource: '@FrameworkBundle/Resources/config/routing/debug.xml'
        prefix: /_debug
