# Configuration for the Symfony web profiler routes
# These routes are only active in the development environment

when@dev:
    web_profiler_wdt:
        resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
        prefix: /_wdt
        # The Web Debug Toolbar route, providing detailed information about the application performance.

    web_profiler_profiler:
        resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
        prefix: /_profiler
        # The profiler route, offering in-depth insights into application requests, database queries, and more.

    web_profiler_debug:
        resource: '@FrameworkBundle/Resources/config/routing/debug.xml'
        prefix: /_debug
        # The debug route, enabling detailed debug information and tools for application development.
