controllers:
    resource: '../src/Controller/'
    type: attribute
    namespace: App\Controller

api:
    resource: '../src/ApiController/'
    type: attribute
    namespace: App\ApiController

admin:
    resource: '../src/AdminController/'
    type: attribute
    namespace: App\AdminController
